remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Bangladesh Road Safety Classifier
Description: An classification API that recognizes condition of Bangladesh Road.

author:
  name: Hridoy Deb Mahin