remote_theme: daviddarnes/alembic@main
plugins:
- jekyll-remote-theme

title: Bangladesh Road Safety Classifier
Description: An classification API that recognizes Bangladesh Road Safety Condition.

Author:
  name: Hridoy Deb Mahin